### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by JosefAschauer** [szaimen/aio-libretranslate#15]
Hi, many thanks for the work you are doing here! I deployed the container within nextcloud AIO 29.0.4.1 but I'm wondering where I can make use of it to translate text / documents from within nextcloud? I cannot find any related context menu (integration addin is installed)

**Comment by szaimen** [comment]
Hi, this translate feature is used in the text app: https://github.com/nextcloud/text?tab=readme-ov-file#nextcloud-text

**Comment by JosefAschauer** [comment]
Many thanks, thats already enabled in my AIO instance but I cannot use the dropdown menue to select a language since it’s not working. An immediately hiding language list pops up but I cannot select anything
Oh, btw,have you seen my other question reg. local-AI? Any ideas? Apparenty someone else had the same question and asked somewhere else
https://github.com/szaimen/aio-local-ai/issues/45

**Comment by szaimen** [comment]
Duplicate of https://github.com/v1r0x/integration_libretranslate/issues/3 (the integration app is not compatible with Nextcloud 29 yet afaics)
